---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verdict-frontend
  namespace: verdict
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verdict-frontend
  template:
    metadata:
      labels:
        app: verdict-frontend
    spec:
      containers:
        - name: frontend
          image: europe-west1-docker.pkg.dev/veridict/veridict/verdict-frontend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: verdict-frontend
  namespace: verdict
spec:
  selector:
    app: verdict-frontend
  ports:
    - port: 80
      targetPort: 80
